Enhancements to support managing npm repositories in nexus
RedHatGov/devsecops-api-collection pull request #13
Opened 2021-11-05 22:03 UTC by dwinchell

We're adding npm support to the ploigos-step-runner. Rather than configuring our snowflake environment by hand, I thought I'd try to out ploigos-service-configs. That lead to this.

Side benefit of doing it this way - we'll be able to more easily update the operator to support npm-based ploigos demos, if we want to do that.

2021-11-05 22:07 UTC, dwinchell commented
For a quick integration test:
```
podman run -d -p 8081:8081 --name nexus docker.io/sonatype/nexus3
NEXUS_ADMIN_PASSWORD=$(podman exec nexus cat /nexus-data/admin.password)
firefox http://localhost:8081/#browse/browse:npm-internal
devsecops-api nexus add-npm-repository -v -U admin -P ${NEXUS_ADMIN_PASSWORD} -r npm-manual http://localhost:8081
firefox http://localhost:8081/#browse/browse:npm-internal
```

2021-11-08 19:40 UTC, dwinchell commented
Added role-related functionality:

```
podman run -d -p 8081:8081 --name nexus docker.io/sonatype/nexus3
sleep 60
devsecops-api nexus add-npm-repository -U admin -P $(podman exec nexus cat /nexus-data/admin.password ) -r npm http://localhost:8081
devsecops-api nexus add-user -U admin -P $(podman exec nexus cat /nexus-data/admin.password ) -u bob -p password  http://localhost:8081
devsecops-api nexus add-role -v -U admin -P $(podman exec nexus cat /nexus-data/admin.password ) -r new-role -p 'nx-repository-view-npm-*-read,nx-repository-view-npm-*-edit,nx-repository-view-npm-*-browse' http://localhost:8081
devsecops-api nexus grant-role-to-user -U admin -P $(podman exec nexus cat /nexus-data/admin.password ) -r new-role -u bob http://localhost:8081
```

2021-11-09 16:33 UTC, andykrohg approved these changes
lgtm

2021-11-09 17:04 UTC, jharmison-redhat requested changes
Just a couple of docstrings on API methods. Otherwise looks good, tyfys.

2021-11-09 17:04 UTC, jharmison-redhat commented on src/devsecops/nexus/nexus.py
> +        Adds a docker format repository backed by the default blobstore
Mind updating the docstrings here?

2021-11-09 17:04 UTC, jharmison-redhat commented on src/devsecops/nexus/nexus.py
> +        Adds a docker format repository backed by the default blobstore
And here

2021-11-09 19:10 UTC, dwinchell commented on src/devsecops/nexus/nexus.py
> +        Adds a docker format repository backed by the default blobstore
oops, good catch

2021-11-09 19:16 UTC, jharmison-redhat approved these changes
lgtm

2021-11-09 19:17 UTC, merged